<div class="rejilla-analitica">
    <section class="panel panel-grafico panel-grafico--ancho"><div class="titulo-panel"><div><i class="bi bi-graph-up-arrow"></i><h2>Tráfico y conversiones</h2><small>Real vs. predicho por IA</small></div><button>Últimos 6 meses</button></div><div class="grafico-barras grande"><?php foreach ([55,72,68,94,83,112,92,126,106,138,119,148] as $i => $altura) :
        ?><span style="--altura:<?= $altura ?>px"><b><?= e(['Ene','Feb','Mar','Abr','May','Jun'][$i % 6]) ?></b></span><?php
                                                                                                                                                                                                                                                                                      endforeach; ?><svg viewBox="0 0 600 180" preserveAspectRatio="none"><polyline points="0,140 100,105 200,88 300,62 400,72 500,48 600,20"/></svg></div></section>
    <section class="panel panel-grafico"><div class="titulo-panel"><div><i class="bi bi-pie-chart-fill"></i><h2>Segmentación de audiencia</h2></div></div><div class="grafico-donut"><div><b>125,430</b><span>usuarios</span></div></div><ul class="leyenda-donut"><li><i class="azul"></i> Nuevos visitantes <b>40%</b></li><li><i class="verde"></i> Recurrentes <b>28%</b></li><li><i class="ambar"></i> Leads <b>18%</b></li><li><i class="violeta"></i> Otros <b>14%</b></li></ul></section>
</div>
<section class="panel acciones-rapidas acciones-ia"><div class="titulo-panel"><div><i class="bi bi-stars"></i><h2>Acciones rápidas con IA</h2></div></div><div><?php foreach (['Analizar campaña','Segmentar audiencia','Generar reporte IA','Optimizar contenido','Sugerir keywords','Crear audiencia similar'] as $accion) :
    ?><button><i class="bi bi-stars"></i><?= e($accion) ?><i class="bi bi-chevron-right"></i></button><?php
                                                                                                                                                               endforeach; ?></div></section>
<div class="rejilla-tres"><section class="panel lista-recomendaciones"><h2>Recomendaciones de IA</h2><?php foreach (['Incrementa la inversión en campañas de video.','Segmenta audiencias similares a tus mejores clientes.','Optimiza títulos y descripciones.','Reactiva usuarios en riesgo.'] as $i => $texto) :
    ?><p><b><?= $i + 1 ?></b><?= e($texto) ?><span>Alto impacto</span></p><?php
                                                                                                     endforeach; ?></section><section class="panel lista-alertas"><h2>Alertas y anomalías</h2><?php foreach (['Caída del 28% en tráfico','Aumento inusual de CPC','Conversión superior al promedio','Nuevo segmento potencial'] as $texto) :
    ?><a href="<?= e(url('admin/campaigns')) ?>"><i class="punto rojo"></i><span><b><?= e($texto) ?></b><small>Detectado por el modelo</small></span></a><?php
                                                                                                     endforeach; ?></section><section class="panel tabla-resumen"><h2>Rendimiento por canal</h2><table class="table"><tbody><?php foreach (['Google Ads','Facebook','Instagram','Email Marketing','SEO'] as $i => $canal) :
    ?><tr><td><?= e($canal) ?></td><td><?= number_format(42320 - ($i * 5400)) ?></td><td><b class="positivo">+<?= 28 - ($i * 3) ?>%</b></td></tr><?php
                                                                                                     endforeach; ?></tbody></table></section></div>
