<section class="panel modulo-filtros"><label><i class="bi bi-search"></i><input type="search" placeholder="Buscar por producto o número de pedido"></label><button><i class="bi bi-calendar3"></i> Últimos 12 meses</button><button><i class="bi bi-funnel"></i> Todos los estados</button><button class="btn btn-primary">Aplicar filtros</button></section>
<section class="panel tabla-mockup"><div class="titulo-panel"><div><i class="bi bi-bag-check"></i><h2>Tus compras (12)</h2></div><button>Más recientes <i class="bi bi-chevron-down"></i></button></div><table class="table"><thead><tr><th>N.º de pedido</th><th>Fecha</th><th>Productos</th><th>Total</th><th>Estado</th><th>Comprobante</th><th>Acciones</th></tr></thead><tbody><?php foreach (['#PED001245','#PED001198','#PED001156','#PED001102','#PED001078'] as $i => $pedido) :
    ?><tr><td><b><?= e($pedido) ?></b></td><td><?= e(['15 mar. 2025','28 feb. 2025','10 ene. 2025','12 dic. 2024','25 nov. 2024'][$i]) ?></td><td><span class="producto-chico"><i class="bi bi-phone"></i></span><span class="producto-chico"><i class="bi bi-earbuds"></i></span> +<?= $i + 1 ?></td><td><b>S/ <?= number_format(499 + ($i * 350), 2) ?></b></td><td><span class="estado estado--verde">Entregado</span></td><td><i class="bi bi-file-earmark-text"></i> Boleta 001-<?= 23456 - $i ?></td><td><button class="btn btn-outline">Ver detalles</button></td></tr><?php
                                                                                                                                                                                                                                                                                                                                                                                    endforeach; ?></tbody></table></section>
<div class="rejilla-listados recomendaciones-compra"><section class="panel"><div class="titulo-panel"><h2>Compra de nuevo tus favoritos</h2><a href="<?= e(url('catalog')) ?>">Ver todos</a></div><div class="productos-horizontales"><?php foreach (['AirPods Pro','JBL Flip 6','Cable USB-C','Cargador 20W'] as $i => $p) :
    ?><article><i class="bi <?= e(['bi-earbuds','bi-speaker','bi-usb-c','bi-plug'][$i]) ?>"></i><b><?= e($p) ?></b><strong>S/ <?= 89 + ($i * 120) ?></strong><a class="btn btn-primary" href="<?= e(url('catalog')) ?>">Comprar de nuevo</a></article><?php
                                                                                                                                                                                                               endforeach; ?></div></section><section class="panel"><div class="titulo-panel"><h2>Recomendado para ti</h2></div><div class="productos-horizontales"><?php foreach (['iPhone 15','Audífonos JBL','Xiaomi Watch'] as $i => $p) :
    ?><article><i class="bi <?= e(['bi-phone','bi-headphones','bi-smartwatch'][$i]) ?>"></i><b><?= e($p) ?></b><strong>S/ <?= 249 + ($i * 450) ?></strong><a class="btn btn-primary" href="<?= e(url('catalog')) ?>">Ver producto</a></article><?php
                                                                                                                                                                                                               endforeach; ?></div></section></div>
